safe:        safe
port:        4002

source:      .
destination: ./_site

future:      true
lsi:         false
markdown_ext: "md"
permalink:   /:year/:month/:title
strict_front_matter: true

title:       Jenner Hanni
description: Personal website for writing, web design, and trip reports.
author:      Jenner Hanni
email:       jennerhanni@gmail.com

exclude:     [_site]

collections:
  travels:
    name: Travels
    url: /travels/
    output: true
    permalink: /travels/:title/
  writing:
    name: Writing
    url: /writing/
    output: true
    permalink: /writing/:title/
