safe:        safe
port:        4002

source:      .
destination: ./_site

future:      true
lsi:         false
markdown_ext: "md"
permalink:   /:year/:month/:title
strict_front_matter: true

title:       Wicker
description: Archived personal website and portfolio, active from 2011-2019.
author:      Wicker
email:       jeh.wicker@gmail.com

exclude:     [_site]

